name: Build Andromeda APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet

      - name: Build APK
        # yes | responde 'y' a todas las preguntas automáticamente
        run: |
          yes | flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Andromeda_App
          path: build/apk/*.apk
